final Map<String, String> arTranslations = {
  'app_name': 'زاد',
  'app_name_ar': 'زاد',
  'welcome_back': 'مرحباً بك مجدداً',
  'login_subtitle': 'قم بجميع معاملاتك المالية بكل سهولة وأمان',
  'phone_number': 'رقم الهاتف',
  'password': 'كلمة السر',
  'forgot_password': 'هل نسيت كلمة السر؟',
  'login': 'تسجيل الدخول',
  'dont_have_account': 'ليس لديك حساب؟ ',
  'sign_up': 'إنشاء حساب',
  'create_account': 'إنشاء حساب جديد',
  'signup_subtitle': 'أدخل بياناتك الشخصية للتسجيل في تطبيق زاد',
  'full_name': 'الاسم بالكامل',
  'email': 'البريد الإلكتروني',
  'national_id': 'الرقم القومي',
  'date_of_birth': 'تاريخ الميلاد',
  'confirm_password': 'تأكيد كلمة السر',
  'upload_id_front': 'رفع صورة البطاقة (الوجه الأمامي)',
  'upload_id_back': 'رفع صورة البطاقة (الوجه الخلفي)',
  'selfie_verification': 'التحقق من الوجه / صورة شخصية',
  'select_image': 'اختر صورة',
  'image_uploaded': 'تم رفع الصورة ✓',
  'submit_registration': 'إرسال طلب التسجيل',
  'already_have_account': 'لديك حساب بالفعل؟ ',
  'otp_verification': 'رمز التحقق (OTP)',
  'otp_subtitle': 'لقد أرسلنا رمز مكون من 6 أرقام إلى هاتفك',
  'verify': 'تأكيد ومتابعة',
  'resend_otp': 'إعادة إرسال الرمز',
  'code_expires_in': 'ينتهي الرمز خلال',
  'reset_password': 'إعادة تعيين كلمة السر',
  'new_password': 'كلمة السر الجديدة',
  'confirm_new_password': 'تأكيد كلمة السر الجديدة',
  'save_password': 'حفظ كلمة السر الجديدة',

  // Main Nav
  'home': 'الرئيسية',
  'internet': 'الباقات',
  'qr': 'رمز QR',
  'history': 'السجل',
  'settings': 'الإعدادات',

  // Home
  'greeting': 'أهلاً، ',
  'available_balance': 'الرصيد المتاح',
  'send': 'إرسال',
  'receive': 'استلام',
  'recent_transactions': 'أحدث المعاملات',
  'see_all': 'عرض الكل',
  'received': 'مستلمة',
  'sent': 'مرسلة',
  'assistant': 'مساعد زاد',
  'assistant_help': 'كيف يمكنني مساعدتك في إدارة أموالك اليوم؟',
  'chat_support': 'الدعم والخدمات',

  // History
  'transaction_history': 'سجل المعاملات',
  'today': 'اليوم',
  'yesterday': 'أمس',
  'earlier': 'سابقاً',
  'search_transactions': 'البحث في المعاملات...',
  'no_transactions': 'لا توجد معاملات',

  // Chat
  'coming_soon': 'قريباً',
  'calling_feature_note': 'ستكون مكالمات الصوت والفيديو متاحة في التحديث القادم.',
  'type_message': 'اكتب رسالتك هنا...',
  'online': 'متصل الآن',
  'offline': 'غير متصل',

  // QR
  'qr_code': 'رمز QR',
  'scan_qr': 'مسح رمز QR',
  'generate_qr': 'إنشاء رمز QR',
  'align_qr': 'قم بمحاذاة رمز QR داخل الإطار لمسحه',
  'demo_scan': 'تجربة المسح',
  'qr_generated': 'رمز QR الخاص بالدفع',
  'scan_to_pay': 'امسح هذا الرمز لتحويل الأموال إلى ',

  // Internet
  'internet_packages': 'باقات الإنترنت والمكالمات',
  'select_country': 'اختر الدولة',
  'buy_package': 'شراء الباقة',
  'package_details': 'تفاصيل الباقة',
  'data_allowance': 'سعة الإنترنت',
  'voice_minutes': 'دقائق المكالمات',
  'sms_allowance': 'الرسائل النصية',
  'validity': 'الصلاحية',
  'days': 'يوم',
  'package_purchased': 'تم شراء الباقة',
  'package_activated': 'تم تفعيل باقتك بنجاح.',
  'confirm_purchase': 'تأكيد الشراء',
  'features': 'مميزات الباقة',

  // Settings
  'user_profile': 'الملف الشخصي',
  'edit_profile': 'تعديل الملف الشخصي',
  'responsible': 'المسؤول (تحديد الموقع)',
  'responsible_desc': 'معرفة موقع الشخص باستخدام رقم هاتفه المسجل.',
  'search_phone': 'أدخل رقم الهاتف المسجل',
  'search': 'البحث عن الموقع',
  'last_updated': 'آخر تحديث:',
  'map_view': 'خريطة الموقع المباشر (GPS)',
  'language': 'اللغة',
  'theme': 'المظهر',
  'light': 'فاتح',
  'dark': 'داكن',
  'system': 'الافتراضي للنظام',
  'notifications': 'الإشعارات',
  'security': 'الأمان والرمز السري',
  'privacy': 'سياسة الخصوصية',
  'help_support': 'المساعدة والدعم',
  'terms_conditions': 'الشروط والأحكام',
  'about_zad': 'عن تطبيق زاد',
  'app_version': 'الإصدار 1.0.0 تجريبي',
  'contact_us': 'تواصل معنا',
  'logout': 'تسجيل الخروج',
  'feature_coming_soon': 'هذه الميزة ستكون متاحة في التحديث القادم.',

  // Send / Receive
  'send_money': 'إرسال أموال',
  'select_recipient': 'اختر المستلم',
  'amount': 'المبلغ',
  'note': 'ملاحظة (اختياري)',
  'continue_btn': 'متابعة',
  'review_transfer': 'مراجعة التحويل',
  'recipient': 'المستلم',
  'transfer_fee': 'رسوم التحويل',
  'total_amount': 'المبلغ الإجمالي',
  'confirm_transfer': 'تأكيد التحويل',
  'transfer_successful': 'تم التحويل بنجاح',
  'transaction_id': 'رقم المعاملة',
  'done': 'تم',
  'view_transaction': 'عرض المعاملة',
  'receive_money': 'استلام أموال',
  'request_money': 'طلب أموال',

  // ZAD Assistant Guides & Help Center
  'asst_title': 'مساعد ZAD',
  'asst_subtitle': 'أنا هنا أشرح لك كل شيء في التطبيق',
  'asst_search_hint': 'اكتب ما تريد معرفته... (مثال: إزاي أبعت فلوس؟)',
  'asst_quick_q_title': 'أسئلة شائعة وسريعة',
  'asst_categories_title': 'استكشف الأقسام',
  'asst_try_now': 'جرب الآن',
  'asst_contextual_title': 'نصيحة الشاشة الحالية',
  'asst_demo_badge': 'وضع تجريبي DEMO',
  'asst_no_results': 'لم نجد دليل مطابِق. جرب البحث عن "إرسال", "استقبال", "QR", "إنترنت", أو "سجل".',

  // Categories
  'asst_cat_account': 'الحساب والملف الشخصي',
  'asst_cat_money': 'الأموال والتحويلات',
  'asst_cat_internet': 'الإنترنت والباقات',
  'asst_cat_qr': 'الدفع برمز QR',
  'asst_cat_history': 'المعاملات والسجل',
  'asst_cat_chat': 'المحادثات وجهات الاتصال',
  'asst_cat_settings': 'الإعدادات والتطبيق',
  'asst_cat_theme': 'المظهر والألوان',
  'asst_cat_language': 'خيارات اللغة',
  'asst_cat_responsible': 'المسؤول والموقع',
  'asst_cat_security': 'الأمان والتحقق KYC',
  'asst_cat_demo': 'عن وضع Demo',

  // Quick Questions
  'q_send': 'كيف أرسل فلوس؟',
  'q_receive': 'كيف أستقبل فلوس؟',
  'q_qr': 'كيف أستخدم QR؟',
  'q_history': 'أين المعاملات؟',
  'q_lang': 'كيف أغير اللغة؟',
  'q_theme': 'كيف أفعل Dark Mode؟',
  'q_internet': 'ما هي باقات الإنترنت؟',
  'q_demo': 'ما هو وضع Demo؟',

  // Topics & Explanations
  't_home_title': 'شرح الصفحة الرئيسية (Home)',
  't_home_sub': 'تعرف على الرصيد، محول العملات، الأزرار السريعة، وأحدث المعاملات.',

  't_send_title': 'دليل إرسال الأموال (Send Money)',
  't_send_sub': 'خطوات تحويل الأموال بسهولة لأي مستلم مسجل في ZAD.',

  't_receive_title': 'دليل استقبال الأموال (Receive Money)',
  't_receive_sub': 'عرض رمز QR الخاص بك أو طلب مبلغ معين من المستلم.',

  't_qr_title': 'دليل استخدام رمز QR',
  't_qr_sub': 'المسح والدفع الفوري أو إنشاء رمز استقبال خاص بك.',

  't_internet_title': 'دليل باقات الإنترنت (Internet)',
  't_internet_sub': 'تصفح وشراء باقات الإنترنت المحلية والدولية في الدول العربية.',

  't_history_title': 'دليل سجل المعاملات (History)',
  't_history_sub': 'متابعة مدفوعاتك المقسمة حسب اليوم، أمس، وقبل ذلك.',

  't_conv_title': 'دليل المحادثات (زر 💬 العائم)',
  't_conv_sub': 'استعراض المحادثات، إشعارات الرسائل الغير مقروءة، وحالة التحويلات.',

  't_chat_title': 'دليل الدردشة المباشرة (Chat)',
  't_chat_sub': 'مراسلة جهات الاتصال وكروت المعاملات المالية المدمجة.',

  't_settings_title': 'دليل الإعدادات (Settings)',
  't_settings_sub': 'إدارة بيانات الحساب، المظهر، اللغة، والأمان.',

  't_lang_title': 'دليل تغيير اللغة (Language)',
  't_lang_sub': 'التبديل بين العربية، الإنجليزية، الفرنسية، والإيطالية.',

  't_theme_title': 'دليل المظهر (Dark & Light Mode)',
  't_theme_sub': 'التبديل بين الوضع الداكن والوضع الفاتح وتفضيلك المحلي.',

  't_resp_title': 'دليل تحديد الموقع (Responsible)',
  't_resp_sub': 'محاكاة تحديد موقع المسجلين برقم الهاتف (بيانات تجريبية).',

  't_login_title': 'دليل تسجيل الدخول (Login)',
  't_login_sub': 'الدخول للحساب باستخدام رقم الهاتف وكلمة السر.',

  't_signup_title': 'دليل التسجيل والتحقق (Sign Up & KYC)',
  't_signup_sub': 'إنشاء حساب جديد ورفع صور البطاقة والتحقق من الوجه.',

  't_otp_title': 'دليل رمز التحقق (OTP)',
  't_otp_sub': 'إدخال رمز الأمان المكون من 6 أرقام (رمز التجربة: 123456).',

  't_txdetail_title': 'دليل تفاصيل المعاملة والحالات',
  't_txdetail_sub': 'معرفة معنى Transaction ID والحالات (مكتملة، قيد الانتظار، فشلت).',

  't_demo_title': 'عن وضع النموذج التجريبي (Demo Mode)',
  't_demo_sub': 'شرح شامل لطبيعة التطبيق التجريبية وكيف أن البيانات تجريبية بالكامل.',

  // Action Buttons
  'btn_start_send': 'ابدأ إرسال الأموال',
  'btn_start_receive': 'ابدأ الاستقبال',
  'btn_try_qr': 'تجربة QR',
  'btn_browse_packages': 'استعرض الباقات',
  'btn_open_history': 'فتح سجل المعاملات',
  'btn_open_settings': 'فتح الإعدادات',
  'btn_try_responsible': 'تجربة تحديد الموقع',
  'btn_go_login': 'تسجيل الدخول',

  // Internet Marketplace
  'mkt_title': 'سوق باقات الإنترنت العربي',
  'mkt_subtitle': 'اختر الدولة واستكشف باقات الإنترنت التجريبية المتاحة.',
  'search_country_hint': 'ابحث عن دولة (مثال: مصر، السعودية، الإمارات)...',
  'popular_destinations': 'الوجهات الشائعة',
  'all_countries': 'جميع الدول العربية (22)',
  'packages_available': 'باقات متاحة',
  'filter_all': 'الكل',
  'best_value_badge': 'الأفضل قيمة',
  'popular_badge': 'الأكثر شيوعاً',
  'demo_package_notice': 'باقة تجريبية DEMO',
  'current_wallet_balance': 'الرصيد الحالي بالمحفظة:',
  'balance_after_purchase': 'الرصيد المتبقي بعد الشراء:',
  'confirm_purchase_title': 'تأكيد شراء الباقة',
  'no_countries_found': 'لم نجد دولاً مطابقة لبحثك.',
  'reset_search': 'إعادة ضبط البحث',
  'select_currency_title': 'اختر عملة الحساب',
  'all_arab_currencies': 'دعم 22 دولة عربية بالكامل 🌍',

  // Chat & Transaction Cards
  'money_sent': 'تم إرسال أموال',
  'money_received': 'تم استلام أموال',
  'to_person': 'إلى',
  'from_person': 'من',
  'tx_completed': 'مكتملة',
  'tx_pending': 'قيد الانتظار',
  'tx_failed': 'فشلت',
  'view_details': 'عرض التفاصيل',
  'transaction_details': 'تفاصيل المعاملة',

  // New Conversation & Chat Management
  'new_conversation': 'محادثة جديدة',
  'search_users': 'البحث عن مستخدم...',
  'start_conversation': 'ابدأ محادثة',
  'no_conversations_yet': 'لا توجد محادثات بعد',
  'send_message': 'إرسال رسالة',
  'start_chat_desc': 'أرسل رسائل نصية أو حول أموالاً فوراً عبر زاد باي',
  'no_users_found': 'لم نجد مستخدمين يطابقون بحثك',

  // Simulated Voice & Video Calling
  'voice_call': 'مكالمة صوتية',
  'video_call': 'مكالمة فيديو',
  'calling': 'جارٍ الاتصال...',
  'connected': 'متصل',
  'muted': 'مكتوم',
  'unmuted': 'غير مكتوم',
  'microphone': 'الميكروفون',
  'speaker': 'مكبر الصوت',
  'camera': 'الكاميرا',
  'camera_off': 'الكاميرا متوقفة',
  'switch_camera': 'تبديل الكاميرا',
  'end_call': 'إنهاء المكالمة',
  'completed': 'مكتملة',
  'cancelled': 'تم الإلغاء',
  'duration': 'المدة',
  'demo_call': 'مكالمة تجريبية (DEMO)',
  'call_again': 'إعادة الاتصال',
  'call_details': 'تفاصيل المكالمة',
};
