final Map<String, String> enTranslations = {
  'app_name': 'ZAD',
  'app_name_ar': 'زاد',
  'welcome_back': 'Welcome Back',
  'login_subtitle': 'Sign in to access your digital wallet',
  'phone_number': 'Phone Number',
  'password': 'Password',
  'forgot_password': 'Forgot Password?',
  'login': 'Log In',
  'dont_have_account': "Don't have an account? ",
  'sign_up': 'Sign Up',
  'create_account': 'Create Account',
  'signup_subtitle': 'Enter your personal details to register with ZAD',
  'full_name': 'Full Name',
  'email': 'Email Address',
  'national_id': 'National ID',
  'date_of_birth': 'Date of Birth',
  'confirm_password': 'Confirm Password',
  'upload_id_front': 'Upload National ID (Front)',
  'upload_id_back': 'Upload National ID (Back)',
  'selfie_verification': 'Selfie / Face Verification',
  'select_image': 'Select Image',
  'image_uploaded': 'Image Uploaded ✓',
  'submit_registration': 'Submit Registration',
  'already_have_account': 'Already have an account? ',
  'otp_verification': 'OTP Verification',
  'otp_subtitle': 'We have sent a 6-digit code to your phone',
  'verify': 'Verify & Continue',
  'resend_otp': 'Resend OTP',
  'code_expires_in': 'Code expires in',
  'reset_password': 'Reset Password',
  'new_password': 'New Password',
  'confirm_new_password': 'Confirm New Password',
  'save_password': 'Save New Password',

  // Main Nav
  'home': 'Home',
  'internet': 'Internet',
  'qr': 'QR',
  'history': 'History',
  'settings': 'Settings',

  // Home
  'greeting': 'Hi, ',
  'available_balance': 'Available Balance',
  'send': 'Send',
  'receive': 'Receive',
  'recent_transactions': 'Recent Transactions',
  'see_all': 'See All',
  'received': 'Received',
  'sent': 'Sent',
  'assistant': 'ZAD Assistant',
  'assistant_help': 'How can I assist you with your finances today?',
  'chat_support': 'Chat Support',

  // History
  'transaction_history': 'Transaction History',
  'today': 'Today',
  'yesterday': 'Yesterday',
  'earlier': 'Earlier',
  'search_transactions': 'Search transactions...',
  'no_transactions': 'No transactions found',

  // Chat
  'coming_soon': 'Coming Soon',
  'calling_feature_note': 'Voice and video calling will be available in a future update.',
  'type_message': 'Type a message...',
  'online': 'Online',
  'offline': 'Offline',

  // QR
  'qr_code': 'QR Code',
  'scan_qr': 'Scan QR',
  'generate_qr': 'Generate QR',
  'align_qr': 'Align QR code within frame to scan',
  'demo_scan': 'Demo Scan',
  'qr_generated': 'Your Payment QR Code',
  'scan_to_pay': 'Scan this code to transfer money to ',

  // Internet
  'internet_packages': 'Internet & Mobile Packages',
  'select_country': 'Select Country',
  'buy_package': 'Buy Package',
  'package_details': 'Package Details',
  'data_allowance': 'Data Allowance',
  'voice_minutes': 'Voice Minutes',
  'sms_allowance': 'SMS',
  'validity': 'Validity',
  'days': 'Days',
  'package_purchased': 'Package Purchased',
  'package_activated': 'Your package has been successfully activated.',
  'confirm_purchase': 'Confirm Purchase',
  'features': 'Package Features',

  // Settings
  'user_profile': 'User Profile',
  'edit_profile': 'Edit Profile',
  'responsible': 'Responsible (Location Lookup)',
  'responsible_desc': 'Find the location of a person using their registered phone number.',
  'search_phone': 'Enter registered phone number',
  'search': 'Search Location',
  'last_updated': 'Last updated:',
  'map_view': 'Live GPS Location Map',
  'language': 'Language',
  'theme': 'Theme Mode',
  'light': 'Light',
  'dark': 'Dark',
  'system': 'System Default',
  'notifications': 'Notifications',
  'security': 'Security & PIN',
  'privacy': 'Privacy Policy',
  'help_support': 'Help & Support',
  'terms_conditions': 'Terms & Conditions',
  'about_zad': 'About ZAD',
  'app_version': 'Version 1.0.0 Demo',
  'contact_us': 'Contact Us',
  'logout': 'Log Out',
  'feature_coming_soon': 'This feature will be available in a future update.',

  // Send / Receive
  'send_money': 'Send Money',
  'select_recipient': 'Select Recipient',
  'amount': 'Amount',
  'note': 'Optional Note (e.g. Dinner)',
  'continue_btn': 'Continue',
  'review_transfer': 'Review Transfer',
  'recipient': 'Recipient',
  'transfer_fee': 'Transfer Fee',
  'total_amount': 'Total Amount',
  'confirm_transfer': 'Confirm Transfer',
  'transfer_successful': 'Transfer Successful',
  'transaction_id': 'Transaction ID',
  'done': 'Done',
  'view_transaction': 'View Transaction',
  'receive_money': 'Receive Money',
  'request_money': 'Request Money',

  // ZAD Assistant Guides & Help Center
  'asst_title': 'ZAD Assistant',
  'asst_subtitle': 'I am here to explain everything in ZAD',
  'asst_search_hint': 'Ask ZAD anything... (e.g. How to send money?)',
  'asst_quick_q_title': 'Quick Questions',
  'asst_categories_title': 'Explore Categories',
  'asst_try_now': 'Try It Now',
  'asst_contextual_title': 'Current Screen Tip',
  'asst_demo_badge': 'DEMO MODE',
  'asst_no_results': 'No matching guide found. Try searching for "send", "qr", "internet", or "history".',

  // Categories
  'asst_cat_account': 'Account & Profile',
  'asst_cat_money': 'Money & Transfers',
  'asst_cat_internet': 'Internet & eSIM',
  'asst_cat_qr': 'QR Payments',
  'asst_cat_history': 'Transactions & History',
  'asst_cat_chat': 'Chat & Contacts',
  'asst_cat_settings': 'Settings & App',
  'asst_cat_theme': 'Appearance & Theme',
  'asst_cat_language': 'Language Options',
  'asst_cat_responsible': 'Responsible & GPS',
  'asst_cat_security': 'Security & KYC',
  'asst_cat_demo': 'About Demo Mode',

  // Quick Questions
  'q_send': 'How do I send money?',
  'q_receive': 'How do I receive money?',
  'q_qr': 'How to use QR code?',
  'q_history': 'Where is transaction history?',
  'q_lang': 'How to change language?',
  'q_theme': 'How to switch Dark Mode?',
  'q_internet': 'What is Internet packages?',
  'q_demo': 'What is ZAD Demo Mode?',

  // Topics & Explanations
  't_home_title': 'Home Screen Overview',
  't_home_sub': 'Understand balance, currency switcher, quick actions, and recent activity.',

  't_send_title': 'Send Money Flow',
  't_send_sub': 'Transfer money step-by-step to any ZAD registered recipient.',

  't_receive_title': 'Receive Money & QR',
  't_receive_sub': 'Display your personal QR or request specific payment amounts.',

  't_qr_title': 'QR Scanner & Generator',
  't_qr_sub': 'Scan to pay merchants or generate your QR for instant transfer.',

  't_internet_title': 'Internet & Roaming Packages',
  't_internet_sub': 'Browse local and international data packages across Arab countries.',

  't_history_title': 'Transaction History & Receipts',
  't_history_sub': 'Track your payments grouped by Today, Yesterday, and Earlier.',

  't_conv_title': 'ZAD Conversations (💬 FAB)',
  't_conv_sub': 'Chat with contacts, check payment statuses, and unread badges.',

  't_chat_title': 'Direct Chat & Payments',
  't_chat_sub': 'Send chat messages and embedded ZAD transaction payment cards.',

  't_settings_title': 'Settings & App Preferences',
  't_settings_sub': 'Manage profile information, appearance, language, and security.',

  't_lang_title': 'Multi-Language Support',
  't_lang_sub': 'Switch seamlessly between Arabic, English, French, and Italian.',

  't_theme_title': 'Dark & Light Mode',
  't_theme_sub': 'Toggle between Midnight Dark and Crisp Light themes anytime.',

  't_resp_title': 'Responsible (Location Lookup)',
  't_resp_sub': 'Simulated GPS lookup by registered phone number.',

  't_login_title': 'Login & Authentication',
  't_login_sub': 'Access your wallet using your phone number and password.',

  't_signup_title': 'Account Registration & KYC',
  't_signup_sub': 'Create a new account with ID upload and face verification.',

  't_otp_title': 'OTP Verification',
  't_otp_sub': 'Verify your identity using 6-digit security code (Demo: 123456).',

  't_txdetail_title': 'Transaction Details & Statuses',
  't_txdetail_sub': 'Understand Transaction IDs, statuses (Completed, Pending, Failed).',

  't_demo_title': 'About ZAD Prototype Demo Mode',
  't_demo_sub': 'Complete overview of ZAD as a high-fidelity fintech prototype.',

  // Action Buttons
  'btn_start_send': 'Start Sending Money',
  'btn_start_receive': 'Start Receiving',
  'btn_try_qr': 'Try QR Code',
  'btn_browse_packages': 'Browse Packages',
  'btn_open_history': 'Open History',
  'btn_open_settings': 'Open Settings',
  'btn_try_responsible': 'Try Location Lookup',
  'btn_go_login': 'Go to Login',

  // Internet Marketplace
  'mkt_title': 'Arab Region Internet Marketplace',
  'mkt_subtitle': 'Choose a country and explore available data packages.',
  'search_country_hint': 'Search country (e.g., Egypt, Saudi Arabia, UAE)...',
  'popular_destinations': 'Popular Destinations',
  'all_countries': 'All 22 Arab Countries',
  'packages_available': 'packages available',
  'filter_all': 'All',
  'best_value_badge': 'BEST VALUE',
  'popular_badge': 'POPULAR',
  'demo_package_notice': 'DEMO PACKAGE',
  'current_wallet_balance': 'Current Wallet Balance:',
  'balance_after_purchase': 'Balance After Purchase:',
  'confirm_purchase_title': 'Confirm Package Purchase',
  'no_countries_found': 'No Arab countries found matching your search.',
  'reset_search': 'Reset Search',
  'select_currency_title': 'Select Wallet Currency',
  'all_arab_currencies': 'Supporting All 22 Arab Countries 🌍',

  // Chat & Transaction Cards
  'money_sent': 'Money Sent',
  'money_received': 'Money Received',
  'to_person': 'To',
  'from_person': 'From',
  'tx_completed': 'Completed',
  'tx_pending': 'Pending',
  'tx_failed': 'Failed',
  'view_details': 'View Details',
  'transaction_details': 'Transaction Details',

  // New Conversation & Chat Management
  'new_conversation': 'New Conversation',
  'search_users': 'Search users...',
  'start_conversation': 'Start a conversation',
  'no_conversations_yet': 'No conversations yet',
  'send_message': 'Send a message',
  'start_chat_desc': 'Send text messages or transfer money instantly with ZAD Pay',
  'no_users_found': 'No users match your search',

  // Simulated Voice & Video Calling
  'voice_call': 'Voice Call',
  'video_call': 'Video Call',
  'calling': 'Calling...',
  'connected': 'Connected',
  'muted': 'Muted',
  'unmuted': 'Unmuted',
  'microphone': 'Microphone',
  'speaker': 'Speaker',
  'camera': 'Camera',
  'camera_off': 'Camera Off',
  'switch_camera': 'Switch Camera',
  'end_call': 'End Call',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'duration': 'Duration',
  'demo_call': 'DEMO CALL',
  'call_again': 'Call Again',
  'call_details': 'Call Details',
};
