final Map<String, String> frTranslations = {
  'app_name': 'ZAD',
  'app_name_ar': 'زاد',
  'welcome_back': 'Bon retour',
  'login_subtitle': 'Connectez-vous à votre portefeuille numérique',
  'phone_number': 'Numéro de téléphone',
  'password': 'Mot de passe',
  'forgot_password': 'Mot de passe oublié?',
  'login': 'Se connecter',
  'dont_have_account': "Vous n'avez pas de compte? ",
  'sign_up': "S'inscrire",
  'create_account': 'Créer un compte',
  'signup_subtitle': 'Entrez vos informations personnelles pour vous inscrire',
  'full_name': 'Nom complet',
  'email': 'Adresse e-mail',
  'national_id': 'Carte nationale d\'identité',
  'date_of_birth': 'Date de naissance',
  'confirm_password': 'Confirmer le mot de passe',
  'upload_id_front': 'Télécharger la CNI (Recto)',
  'upload_id_back': 'Télécharger la CNI (Verso)',
  'selfie_verification': 'Vérification faciale / Selfie',
  'select_image': 'Sélectionner une image',
  'image_uploaded': 'Image téléchargée ✓',
  'submit_registration': 'Soumettre l\'inscription',
  'already_have_account': 'Vous avez déjà un compte? ',
  'otp_verification': 'Vérification OTP',
  'otp_subtitle': 'Un code à 6 chiffres a été envoyé sur votre téléphone',
  'verify': 'Vérifier et continuer',
  'resend_otp': 'Renvoyer le code',
  'code_expires_in': 'Code expire dans',
  'reset_password': 'Réinitialiser le mot de passe',
  'new_password': 'Nouveau mot de passe',
  'confirm_new_password': 'Confirmer le nouveau mot de passe',
  'save_password': 'Enregistrer',

  // Main Nav
  'home': 'Accueil',
  'internet': 'Internet',
  'qr': 'Code QR',
  'history': 'Historique',
  'settings': 'Paramètres',

  // Home
  'greeting': 'Bonjour, ',
  'available_balance': 'Solde disponible',
  'send': 'Envoyer',
  'receive': 'Recevoir',
  'recent_transactions': 'Transactions récentes',
  'see_all': 'Tout voir',
  'received': 'Reçu',
  'sent': 'Envoyé',
  'assistant': 'Assistant ZAD',
  'assistant_help': 'Comment puis-je vous aider aujourd\'hui?',
  'chat_support': 'Support client',

  // History
  'transaction_history': 'Historique des transactions',
  'today': 'Aujourd\'hui',
  'yesterday': 'Hier',
  'earlier': 'Plus tôt',
  'search_transactions': 'Rechercher une transaction...',
  'no_transactions': 'Aucune transaction trouvée',

  // Chat
  'coming_soon': 'Bientôt disponible',
  'calling_feature_note': 'Les appels vocaux et vidéo seront disponibles dans une prochaine mise à jour.',
  'type_message': 'Écrivez un message...',
  'online': 'En ligne',
  'offline': 'Hors ligne',

  // QR
  'qr_code': 'Code QR',
  'scan_qr': 'Scanner QR',
  'generate_qr': 'Générer QR',
  'align_qr': 'Alignez le code QR dans le cadre',
  'demo_scan': 'Scan démo',
  'qr_generated': 'Votre QR de paiement',
  'scan_to_pay': 'Scannez ce code pour envoyer de l\'argent à ',

  // Internet
  'internet_packages': 'Forfaits Internet & Mobile',
  'select_country': 'Sélectionner le pays',
  'buy_package': 'Acheter le forfait',
  'package_details': 'Détails du forfait',
  'data_allowance': 'Données Internet',
  'voice_minutes': 'Minutes d\'appel',
  'sms_allowance': 'SMS',
  'validity': 'Validité',
  'days': 'Jours',
  'package_purchased': 'Forfait acheté',
  'package_activated': 'Votre forfait a été activé avec succès.',
  'confirm_purchase': 'Confirmer l\'achat',
  'features': 'Caractéristiques',

  // Settings
  'user_profile': 'Profil utilisateur',
  'edit_profile': 'Modifier le profil',
  'responsible': 'Responsable (Localisation)',
  'responsible_desc': 'Trouvez la position d\'une personne via son numéro de téléphone enregistré.',
  'search_phone': 'Entrez le numéro de téléphone enregistré',
  'search': 'Rechercher la position',
  'last_updated': 'Dernière mise à jour:',
  'map_view': 'Carte de localisation GPS',
  'language': 'Langue',
  'theme': 'Thème',
  'light': 'Clair',
  'dark': 'Sombre',
  'system': 'Système par défaut',
  'notifications': 'Notifications',
  'security': 'Sécurité & PIN',
  'privacy': 'Politique de confidentialité',
  'help_support': 'Aide & Support',
  'terms_conditions': 'Conditions d\'utilisation',
  'about_zad': 'À propos de ZAD',
  'app_version': 'Version 1.0.0 Démo',
  'contact_us': 'Nous contacter',
  'logout': 'Se déconnecter',
  'feature_coming_soon': 'Cette fonctionnalité sera disponible prochainement.',

  // Send / Receive
  'send_money': 'Envoyer de l\'argent',
  'select_recipient': 'Sélectionner le destinataire',
  'amount': 'Montant',
  'note': 'Note optionnelle',
  'continue_btn': 'Continuer',
  'review_transfer': 'Vérifier le transfert',
  'recipient': 'Destinataire',
  'transfer_fee': 'Frais de transfert',
  'total_amount': 'Montant total',
  'confirm_transfer': 'Confirmer le transfert',
  'transfer_successful': 'Transfert réussi',
  'transaction_id': 'ID de transaction',
  'done': 'Terminé',
  'view_transaction': 'Voir la transaction',
  'receive_money': 'Recevoir de l\'argent',
  'request_money': 'Demander de l\'argent',

  // ZAD Assistant Guides & Help Center
  'asst_title': 'Assistant ZAD',
  'asst_subtitle': 'Je suis là pour tout vous expliquer dans ZAD',
  'asst_search_hint': 'Posez une question... (ex: Comment envoyer?)',
  'asst_quick_q_title': 'Questions fréquentes',
  'asst_categories_title': 'Explorer les catégories',
  'asst_try_now': 'Essayer maintenant',
  'asst_contextual_title': 'Conseil pour cet écran',
  'asst_demo_badge': 'MODE DÉMO',
  'asst_no_results': 'Aucun guide trouvé. Essayez de chercher "envoyer", "qr", ou "historique".',

  // Categories
  'asst_cat_account': 'Compte & Profil',
  'asst_cat_money': 'Argent & Transferts',
  'asst_cat_internet': 'Internet & eSIM',
  'asst_cat_qr': 'Paiements QR',
  'asst_cat_history': 'Transactions & Historique',
  'asst_cat_chat': 'Discussions & Contacts',
  'asst_cat_settings': 'Paramètres',
  'asst_cat_theme': 'Apparence & Thème',
  'asst_cat_language': 'Options de langue',
  'asst_cat_responsible': 'Responsable & Localisation',
  'asst_cat_security': 'Sécurité & KYC',
  'asst_cat_demo': 'À propos du mode démo',

  // Quick Questions
  'q_send': 'Comment envoyer de l\'argent?',
  'q_receive': 'Comment recevoir de l\'argent?',
  'q_qr': 'Comment utiliser le code QR?',
  'q_history': 'Où est l\'historique?',
  'q_lang': 'Comment changer de langue?',
  'q_theme': 'Comment activer le mode sombre?',
  'q_internet': 'Quels sont les forfaits Internet?',
  'q_demo': 'Qu\'est-ce que le mode Démo?',

  // Topics & Explanations
  't_home_title': 'Présentation de l\'écran d\'accueil',
  't_home_sub': 'Comprenez le solde, les devises, et les actions rapides.',

  't_send_title': 'Guide d\'envoi d\'argent',
  't_send_sub': 'Transférez de l\'argent étape par étape à n\'importe quel destinataire ZAD.',

  't_receive_title': 'Guide de réception d\'argent',
  't_receive_sub': 'Affichez votre QR personnel ou demandez un montant spécifique.',

  't_qr_title': 'Scanner & Générateur QR',
  't_qr_sub': 'Scannez pour payer ou géférez votre code QR pour un transfert instantané.',

  't_internet_title': 'Forfaits Internet & Roaming',
  't_internet_sub': 'Parcourez les forfaits de données locaux et internationaux.',

  't_history_title': 'Historique & Reçus',
  't_history_sub': 'Suivez vos paiements regroupés par Aujourd\'hui, Hier et Plus tôt.',

  't_conv_title': 'Conversations ZAD (Bouton 💬)',
  't_conv_sub': 'Consultez la liste des contacts et le statut des paiements.',

  't_chat_title': 'Chat direct & Paiements',
  't_chat_sub': 'Envoyez des messages et des cartes de paiement intégrées.',

  't_settings_title': 'Paramètres de l\'application',
  't_settings_sub': 'Gérez votre profil, l\'apparence, la langue et la sécurité.',

  't_lang_title': 'Support multilingue',
  't_lang_sub': 'Basculez entre l\'arabe, l\'anglais, le français et l\'italien.',

  't_theme_title': 'Mode sombre & clair',
  't_theme_sub': 'Basculez entre les thèmes Sombre et Clair à tout moment.',

  't_resp_title': 'Responsable (Localisation)',
  't_resp_sub': 'Recherche de localisation simulée par numéro de téléphone.',

  't_login_title': 'Connexion & Authentification',
  't_login_sub': 'Accédez à votre portefeuille avec votre numéro et mot de passe.',

  't_signup_title': 'Inscription & Vérification KYC',
  't_signup_sub': 'Créer un compte avec téléversement de la CNI et vérification faciale.',

  't_otp_title': 'Vérification OTP',
  't_otp_sub': 'Vérifiez votre identité avec le code à 6 chiffres (Démo: 123456).',

  't_txdetail_title': 'Détails des transactions',
  't_txdetail_sub': 'Comprenez les ID de transaction et les statuts (Terminé, En attente, Échoué).',

  't_demo_title': 'À propos du mode prototype Démo',
  't_demo_sub': 'Présentation complète de ZAD en tant que prototype fintech.',

  // Action Buttons
  'btn_start_send': 'Commencer l\'envoi',
  'btn_start_receive': 'Commencer la réception',
  'btn_try_qr': 'Essayer le code QR',
  'btn_browse_packages': 'Parcourir les forfaits',
  'btn_open_history': 'Ouvrir l\'historique',
  'btn_open_settings': 'Ouvrir les paramètres',
  'btn_try_responsible': 'Essayer la localisation',
  'btn_go_login': 'Se connecter',

  // Internet Marketplace
  'mkt_title': 'Marché Internet de la Région Arabe',
  'mkt_subtitle': 'Choisissez un pays et explorez les forfaits de données disponibles.',
  'search_country_hint': 'Rechercher un pays (ex: Égypte, Saoudite, Émirats)...',
  'popular_destinations': 'Destinations Populaires',
  'all_countries': 'Tous les 22 Pays Arabes',
  'packages_available': 'forfaits disponibles',
  'filter_all': 'Tous',
  'best_value_badge': 'MEILLEUR PRIX',
  'popular_badge': 'POPULAIRE',
  'demo_package_notice': 'FORFAIT DÉMO',
  'current_wallet_balance': 'Solde Actuel du Portefeuille:',
  'balance_after_purchase': 'Solde Après Achat:',
  'confirm_purchase_title': 'Confirmer l\'Achat du Forfait',
  'no_countries_found': 'Aucun pays arabe ne correspond à votre recherche.',
  'reset_search': 'Réinitialiser la Recherche',
};
