final Map<String, String> itTranslations = {
  'app_name': 'ZAD',
  'app_name_ar': 'زاد',
  'welcome_back': 'Bentornato',
  'login_subtitle': 'Accedi al tuo portafoglio digitale',
  'phone_number': 'Numero di telefono',
  'password': 'Password',
  'forgot_password': 'Password dimenticata?',
  'login': 'Accedi',
  'dont_have_account': 'Non hai un account? ',
  'sign_up': 'Registrati',
  'create_account': 'Crea un account',
  'signup_subtitle': 'Inserisci i tuoi dati personali per registrarti a ZAD',
  'full_name': 'Nome completo',
  'email': 'Indirizzo e-mail',
  'national_id': 'Carta d\'identità',
  'date_of_birth': 'Data di nascita',
  'confirm_password': 'Conferma password',
  'upload_id_front': 'Carica Carta d\'identità (Fronte)',
  'upload_id_back': 'Carica Carta d\'identità (Retro)',
  'selfie_verification': 'Verifica facciale / Selfie',
  'select_image': 'Seleziona immagine',
  'image_uploaded': 'Immagine caricata ✓',
  'submit_registration': 'Invia registrazione',
  'already_have_account': 'Hai già un account? ',
  'otp_verification': 'Verifica OTP',
  'otp_subtitle': 'Abbiamo inviato un codice a 6 cifre al tuo telefono',
  'verify': 'Verifica e continua',
  'resend_otp': 'Reinvia codice',
  'code_expires_in': 'Il codice scade in',
  'reset_password': 'Reimposta password',
  'new_password': 'Nuova password',
  'confirm_new_password': 'Conferma nuova password',
  'save_password': 'Salva password',

  // Main Nav
  'home': 'Home',
  'internet': 'Internet',
  'qr': 'Codice QR',
  'history': 'Cronologia',
  'settings': 'Impostazioni',

  // Home
  'greeting': 'Ciao, ',
  'available_balance': 'Saldo disponibile',
  'send': 'Invia',
  'receive': 'Ricevi',
  'recent_transactions': 'Transazioni recenti',
  'see_all': 'Vedi tutto',
  'received': 'Ricevuto',
  'sent': 'Inviato',
  'assistant': 'Assistente ZAD',
  'assistant_help': 'Come posso aiutarti oggi con le tue finanze?',
  'chat_support': 'Supporto chat',

  // History
  'transaction_history': 'Cronologia transazioni',
  'today': 'Oggi',
  'yesterday': 'Ieri',
  'earlier': 'Prima',
  'search_transactions': 'Cerca transazioni...',
  'no_transactions': 'Nessuna transazione trovata',

  // Chat
  'coming_soon': 'In arrivo',
  'calling_feature_note': 'Le chiamate vocali e video saranno disponibili in un futuro aggiornamento.',
  'type_message': 'Scrivi un messaggio...',
  'online': 'Online',
  'offline': 'Offline',

  // QR
  'qr_code': 'Codice QR',
  'scan_qr': 'Scansiona QR',
  'generate_qr': 'Genera QR',
  'align_qr': 'Inquadra il codice QR nel riquadro',
  'demo_scan': 'Scansione demo',
  'qr_generated': 'Il tuo QR di pagamento',
  'scan_to_pay': 'Scansiona questo codice per inviare denaro a ',

  // Internet
  'internet_packages': 'Pacchetti Internet & Mobile',
  'select_country': 'Seleziona paese',
  'buy_package': 'Acquista pacchetto',
  'package_details': 'Dettagli pacchetto',
  'data_allowance': 'Giga Internet',
  'voice_minutes': 'Minuti di chiamata',
  'sms_allowance': 'SMS',
  'validity': 'Validità',
  'days': 'Giorni',
  'package_purchased': 'Pacchetto acquistato',
  'package_activated': 'Il tuo pacchetto è stato attivato con successo.',
  'confirm_purchase': 'Conferma acquisto',
  'features': 'Caratteristiche',

  // Settings
  'user_profile': 'Profilo utente',
  'edit_profile': 'Modifica profilo',
  'responsible': 'Responsabile (Posizione)',
  'responsible_desc': 'Trova la posizione di una persona tramite il numero di telefono.',
  'search_phone': 'Inserisci numero di telefono',
  'search': 'Cerca posizione',
  'last_updated': 'Ultimo aggiornamento:',
  'map_view': 'Mappa GPS live',
  'language': 'Lingua',
  'theme': 'Tema',
  'light': 'Chiaro',
  'dark': 'Scuro',
  'system': 'Predefinito di sistema',
  'notifications': 'Notifiche',
  'security': 'Sicurezza & PIN',
  'privacy': 'Informativa sulla privacy',
  'help_support': 'Aiuto & Supporto',
  'terms_conditions': 'Termini & Condizioni',
  'about_zad': 'Informazioni su ZAD',
  'app_version': 'Versione 1.0.0 Demo',
  'contact_us': 'Contattaci',
  'logout': 'Disconnettiti',
  'feature_coming_soon': 'Questa funzione sarà disponibile a breve.',

  // Send / Receive
  'send_money': 'Invia denaro',
  'select_recipient': 'Seleziona destinatario',
  'amount': 'Importo',
  'note': 'Nota opzionale',
  'continue_btn': 'Continua',
  'review_transfer': 'Rivedi trasferimento',
  'recipient': 'Destinatario',
  'transfer_fee': 'Commissione',
  'total_amount': 'Importo totale',
  'confirm_transfer': 'Conferma trasferimento',
  'transfer_successful': 'Trasferimento riuscito',
  'transaction_id': 'ID transazione',
  'done': 'Fatto',
  'view_transaction': 'Visualizza transazione',
  'receive_money': 'Ricevi denaro',
  'request_money': 'Richiedi denaro',

  // ZAD Assistant Guides & Help Center
  'asst_title': 'Assistente ZAD',
  'asst_subtitle': 'Sono qui per spiegarti tutto in ZAD',
  'asst_search_hint': 'Chiedi a ZAD... (es. Come inviare denaro?)',
  'asst_quick_q_title': 'Domande frequenti',
  'asst_categories_title': 'Esplora categorie',
  'asst_try_now': 'Prova ora',
  'asst_contextual_title': 'Consiglio per questa schermata',
  'asst_demo_badge': 'MODALITÀ DEMO',
  'asst_no_results': 'Nessuna guida trovata. Prova a cercare "invia", "qr" o "cronologia".',

  // Categories
  'asst_cat_account': 'Account & Profilo',
  'asst_cat_money': 'Denaro & Trasferimenti',
  'asst_cat_internet': 'Internet & eSIM',
  'asst_cat_qr': 'Pagamenti QR',
  'asst_cat_history': 'Transazioni & Cronologia',
  'asst_cat_chat': 'Chat & Contatti',
  'asst_cat_settings': 'Impostazioni',
  'asst_cat_theme': 'Aspetto & Tema',
  'asst_cat_language': 'Opzioni lingua',
  'asst_cat_responsible': 'Responsabile & Posizione',
  'asst_cat_security': 'Sicurezza & KYC',
  'asst_cat_demo': 'Informazioni modalità Demo',

  // Quick Questions
  'q_send': 'Come inviare denaro?',
  'q_receive': 'Come ricevere denaro?',
  'q_qr': 'Come usare il codice QR?',
  'q_history': 'Dov\'è la cronologia?',
  'q_lang': 'Come cambiare lingua?',
  'q_theme': 'Come attivare la modalità scura?',
  'q_internet': 'Cosa sono i pacchetti Internet?',
  'q_demo': 'Cos\'è la modalità Demo?',

  // Topics & Explanations
  't_home_title': 'Panoramica schermata Home',
  't_home_sub': 'Comprendi il saldo, le valute e le azioni rapide.',

  't_send_title': 'Guida all\'invio di denaro',
  't_send_sub': 'Trasferisci denaro passo dopo passo a qualsiasi destinatario ZAD.',

  't_receive_title': 'Guida alla ricezione di denaro',
  't_receive_sub': 'Mostra il tuo QR personale o richiedi un importo specifico.',

  't_qr_title': 'Scanner & Generatore QR',
  't_qr_sub': 'Scansiona per pagare o genera il tuo codice QR.',

  't_internet_title': 'Pacchetti Internet & Roaming',
  't_internet_sub': 'Esplora i pacchetti dati locali e internazionali.',

  't_history_title': 'Cronologia & Ricevute',
  't_history_sub': 'Traccia i tuoi pagamenti raggruppati per Oggi, Ieri e Prima.',

  't_conv_title': 'Conversazioni ZAD (Pulsante 💬)',
  't_conv_sub': 'Visualizza l\'elenco dei contatti e lo stato dei pagamenti.',

  't_chat_title': 'Chat diretta & Pagamenti',
  't_chat_sub': 'Invia messaggi e schede di pagamento integrate.',

  't_settings_title': 'Impostazioni dell\'app',
  't_settings_sub': 'Gestisci il tuo profilo, l\'aspetto, la lingua e la sicurezza.',

  't_lang_title': 'Supporto multilingue',
  't_lang_sub': 'Passa tra arabo, inglese, francese e italiano.',

  't_theme_title': 'Modalità scura e chiara',
  't_theme_sub': 'Passa tra i temi Scuro e Chiaro in qualsiasi momento.',

  't_resp_title': 'Responsabile (Posizione)',
  't_resp_sub': 'Ricerca della posizione simulata tramite numero di telefono.',

  't_login_title': 'Accesso & Autenticazione',
  't_login_sub': 'Accedi al tuo portafoglio con numero e password.',

  't_signup_title': 'Registrazione & Verifica KYC',
  't_signup_sub': 'Crea un account con caricamento carta d\'identità e selfie.',

  't_otp_title': 'Verifica OTP',
  't_otp_sub': 'Verifica la tua identità con il codice a 6 cifre (Demo: 123456).',

  't_txdetail_title': 'Dettagli transazione',
  't_txdetail_sub': 'Comprendi gli ID transazione e gli stati (Completato, In sospeso, Fallito).',

  't_demo_title': 'Informazioni sulla modalità Demo',
  't_demo_sub': 'Panoramica completa di ZAD come prototipo fintech.',

  // Action Buttons
  'btn_start_send': 'Inizia ad inviare',
  'btn_start_receive': 'Inizia a ricevere',
  'btn_try_qr': 'Prova codice QR',
  'btn_browse_packages': 'Esplora pacchetti',
  'btn_open_history': 'Apri cronologia',
  'btn_open_settings': 'Apri impostazioni',
  'btn_try_responsible': 'Prova ricerca posizione',
  'btn_go_login': 'Vai all\'accesso',

  // Internet Marketplace
  'mkt_title': 'Mercato Internet Regione Araba',
  'mkt_subtitle': 'Scegli un paese ed esplora i pacchetti dati disponibili.',
  'search_country_hint': 'Cerca paese (es: Egitto, Arabia Saudita, Emirati)...',
  'popular_destinations': 'Destinazioni Popolari',
  'all_countries': 'Tutti i 22 Paesi Arabi',
  'packages_available': 'pacchetti disponibili',
  'filter_all': 'Tutti',
  'best_value_badge': 'MIGLIOR PREZZO',
  'popular_badge': 'POPOLARE',
  'demo_package_notice': 'PACCHETTO DEMO',
  'current_wallet_balance': 'Saldo Attuale Portafoglio:',
  'balance_after_purchase': 'Saldo Dopo l\'Acquisto:',
  'confirm_purchase_title': 'Conferma Acquisto Pacchetto',
  'no_countries_found': 'Nessun paese arabo trovato corrispondente alla ricerca.',
  'reset_search': 'Ripristina Ricerca',
};
